# Generated by Django 5.1.5 on 2025-01-30 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicine",
            name="active_ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="availability",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
