# Generated by Django 5.1.5 on 2025-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_medicine_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="availability",
            field=models.CharField(
                choices=[("in_stock", "In Stock"), ("out_of_stock", "Out of Stock")],
                default="in_stock",
                max_length=20,
            ),
        ),
    ]
