# Generated by Django 5.2.1 on 2025-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='catalog.symptom'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
