# Generated by Django 5.1.6 on 2025-05-30 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_medicine_symptoms_alter_symptom_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.ManyToManyField(blank=True, related_name='medicine_lists', to='catalog.medicine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
